---
  - hosts: webservers
    become: yes
    tasks:
    
      - name: Print the gateway for each host when defined
        ansible.builtin.debug:
          msg: "{{ ansible_host }}"

      - name: create a file with your ip as its content
        copy:
          dest: /home/automation/ip_addr.txt
          content: |
            "{{ ansible_host }}"
