---
  - hosts: webservers 
    become: yes
    tasks:
      - name: install the python library
        yum:
          name: libsemanage-python
          state: present
      - name: Set httpd_can_network_connect flag on reboot resiliant
        seboolean:
          name: httpd_can_network_connect
          state: yes
          persistent: yes
